### ISSUE TITLE
Add java options runtime feature

### ISSUE THREAD

**Issue by UnbackedFan** [SergeMerzliakov/installmation#3]
Would be nice to have a feature that allows options to be passed to the Java runtime.

**Comment by SergeMerzliakov** [comment]
Thats a good idea. Will add it.

**Comment by SergeMerzliakov** [comment]
> Would be nice to have a feature that allows options to be passed to the Java runtime.

Thats a good question. You want to pass options to JVM running jpackage, the JVM to be deployed, or both?

**Comment by UnbackedFan** [comment]
Personally I found that I needed the feature for the JVM that is deployed with the app.

**Comment by SergeMerzliakov** [comment]
> Personally I found that I needed the feature for the JVM that is deployed with the app.

OK. That is a simple fix. will get it done and close this issue.

**Comment by SergeMerzliakov** [comment]
Feature added in version 0.2.5
